"""AIKernel Python bindings."""

from .bindings import (
    AIKernelNativeError,
    ForwardResult,
    forward,
    forward_result,
    load_model,
    load_model_result,
    unload_model,
    unload_model_result,
)
from .managed import (
    ManagedAssemblySet,
    RuntimeLayout,
    managed_assemblies,
    require_managed_assemblies,
    runtime_layout,
)
from .monads import (
    AsyncEither,
    AsyncOption,
    AsyncResult,
    Either,
    Failure,
    Left,
    Nothing,
    Option,
    Result,
    Right,
    Some,
    Success,
    Try,
    async_do,
    async_either,
    async_option,
    async_result,
    do,
)

__all__ = [
    "AIKernelNativeError",
    "AsyncEither",
    "AsyncOption",
    "AsyncResult",
    "Either",
    "Failure",
    "ForwardResult",
    "Left",
    "ManagedAssemblySet",
    "Nothing",
    "Option",
    "Result",
    "RuntimeLayout",
    "Right",
    "Some",
    "Success",
    "Try",
    "async_do",
    "async_either",
    "async_option",
    "async_result",
    "do",
    "forward",
    "forward_result",
    "load_model",
    "load_model_result",
    "managed_assemblies",
    "require_managed_assemblies",
    "runtime_layout",
    "unload_model",
    "unload_model_result",
]

__version__ = "0.0.5"
